<!DOCTYPE html>
<html lang="en">
      <head>
            <meta http-equiv="content-type" content="text/html; charset=utf-8" />
            <title><?php echo $currentTitle ?></title>
            <link href="https://fonts.googleapis.com/css?family=Dokdo|Gloria+Hallelujah|Indie+Flower|Jua|Kalam" rel="stylesheet">
            <link rel="stylesheet" type="text/css" href="./css/normalize.min.css">
            <link rel="stylesheet" type="text/css" href="./css/styles.css">
      </head>
      <body>
