<!--nav bar-->

<nav>
	<ul>
		<li><a href="history.php"><img src="./media/sc.png" title="shinchan1" alt="shinchan1">History and Basic Information</a></li>
		<li><a href="media.php"><img src="./media/sc.png" title="shinchan1" alt="shinchan1">Anime</a></li>
		<li><a href="characters.php"><img src="./media/sc.png" title="shinchan1" alt="shinchan1">Main Characters</a></li>
	</ul>
</nav>

<!--end of nav bar-->
